name: CI

on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check
        run: make vet

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1

      - name: Test
        run: make test
